services:
  doom-app:
    container_name: doom-app
    image: m1guelch/doom-docker:latest
    restart: always
    ports: 
        - 8085:8080
    networks:
      - doom-net

networks:
  doom-net:
    driver: bridge
